// <auto-generated />
namespace Bibliotheek.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class recup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recup));
        
        string IMigrationMetadata.Id
        {
            get { return "201309160855203_recup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
