// <auto-generated />
namespace Bibliotheek.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class titel_required : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(titel_required));
        
        string IMigrationMetadata.Id
        {
            get { return "201310231235234_titel_required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
