// <auto-generated />
namespace Bibliotheek.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class test2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test2));
        
        string IMigrationMetadata.Id
        {
            get { return "201311060724217_test2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
